### ISSUE TITLE
ARB .bsv File Generation

### ISSUE THREAD

**Issue by stepanurban** [jarjuk/UTG900#2]
Hi @jarjuk,
first thanks for this amazing tool! I would like to ask if there is some information about ARB (.bsv) wave files used to generate custom waves. I have sampled values that I would like to generate and existing tool is not very convenient for this. Are there any other tools that can generate these format or is somewhere definition of this format?

Thank you

**Comment by jarjuk** [comment]
Hello @stepanurban,
Thank Your your kind words. Unfortunately I cannot help you with .bsv file format. The example file, which is included in the repo was created on eeblog.com site https://www.eevblog.com/forum/testgear/uni-t-utg932utg962-200msas-function-arbitrary-waveform-generator-220394/msg3537786/#msg3537786 .  He can be contacted here on github https://github.com/W3AXL - maybe he can help you.

BR Jukka,

PS. Have you noticed that I have migrated UTG900 functionality to https://github.com/jarjuk/ebench -repo. Version in that repo should be capable to do the same things as UTG900 plus it can also use factory installed wave forms.
